# Docker Compose für MCP.Guard mit AI Storage Support

services:
  # Hauptanwendung - MCP.Guard Server & Client
  mcp-guard-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mcp-guard-app
    ports:
      - '5173:5173' # Vite Dev Server
      - '3000:3000' # Express Server
    environment:
      - NODE_ENV=development
      - AI_STORAGE_TYPE=hybrid
      - DATABASE_URL=postgresql://mcp_guard_user:mcp_guard_password@postgres:5432/mcp_guard_ai_storage
      - REDIS_URL=redis://redis:6379
      - MCP_SERVER_ID=mcp-guard-main-server
      - PROJECT_ID=mcp-guard-monitoring
      - ORGANIZATION_ID=mcp-guard-org
      - PYTHON_API_URL=http://mcp-guard-python-ai:8000
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      python-ai:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules
      - ./python-framework:/app/python-framework
    command: npm run dev
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/api/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - mcp-guard-network

  # PostgreSQL für AI Progress Storage
  postgres:
    image: postgres:15-alpine
    container_name: mcp-guard-postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: mcp_guard_ai_storage
      POSTGRES_USER: mcp_guard_user
      POSTGRES_PASSWORD: mcp_guard_password
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    healthcheck:
      test:
        ['CMD-SHELL', 'pg_isready -U mcp_guard_user -d mcp_guard_ai_storage -h localhost -p 5432']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - mcp-guard-network

  # Redis für Caching und Session Management
  redis:
    image: redis:7-alpine
    container_name: mcp-guard-redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', '--raw', 'incr', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - mcp-guard-network

  # Test MCP Server für Integration Tests
  test-mcp-server:
    build:
      context: ./docker/test-mcp-server
      dockerfile: Dockerfile
    container_name: test-mcp-server
    ports:
      - '3001:3001'
    environment:
      - CONFIG_PATH=/app/config/basic-test.json
      - NODE_ENV=production
      - MCP_SERVER_ID=test-mcp-server
      - AI_STORAGE_TYPE=memory
    volumes:
      - ./docker/test-mcp-server/config:/app/config:ro
    healthcheck:
      test: ['CMD', 'node', 'dist/health-check.js']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - mcp-guard-network

  # Python Framework über npm package
  python-ai:
    build:
      context: .
      dockerfile: docker/python-framework/Dockerfile
    container_name: mcp-guard-python-ai
    ports:
      - '8000:8000'
    environment:
      - AI_STORAGE_TYPE=hybrid
      - DATABASE_URL=postgresql://mcp_guard_user:mcp_guard_password@postgres:5432/mcp_guard_ai_storage
      - REDIS_URL=redis://redis:6379
      - MCP_GUARD_FRAMEWORK_MODE=api
      - MCP_GUARD_FRAMEWORK_PORT=8000
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./python-framework/ai_models:/app/ai_models
      - ./python-framework/data:/app/data
    working_dir: /app
    command: python api_server.py
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8000/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - mcp-guard-network

# Test Manager Service is now integrated as npm package

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  mcp-guard-network:
    driver: bridge
