version: '3.8'

services:
  # Lokales Docker Registry
  registry:
    image: registry:2
    restart: always
    ports:
      - "5000:5000"
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /var/lib/registry
    volumes:
      - registry-data:/var/lib/registry
      - ./registry-config.yml:/etc/docker/registry/config.yml
    networks:
      - registry-network

  # Registry UI für bessere Übersicht
  registry-ui:
    image: joxit/docker-registry-ui:static
    restart: always
    ports:
      - "5001:80"
    environment:
      - REGISTRY_TITLE=IMF Local Registry
      - REGISTRY_URL=http://registry:5000
      - DELETE_IMAGES=true
      - SHOW_CONTENT_DIGEST=true
      - CATALOG_ELEMENTS_LIMIT=1000
    networks:
      - registry-network
    depends_on:
      - registry

volumes:
  registry-data:

networks:
  registry-network:
    driver: bridge