# Intelligent Monitoring Framework Configuration
server_type: generic
monitoring_interval: 120
learning_enabled: false
auto_remediation: true
log_level: DEBUG
data_dir: /tmp/imf

# Log files to monitor
log_files:
  - path: "/var/log/system.log"
    type: "system"
  - path: "/var/log/app.log"
    type: "application"

# Plugin configuration
plugins:
  collectors:
    - log_file_collector
    - system_metrics_collector
  detectors:
    - log_pattern_detector
    - threshold_detector
  remediators:
    - system_remediation

# Threshold configuration
thresholds:
  cpu_usage:
    warning: 80
    critical: 95
  memory_usage:
    warning: 85
    critical: 95
  disk_usage:
    warning: 85
    critical: 95