server_type: generic
monitoring_interval: 30
learning_enabled: true
auto_remediation: false
log_level: INFO
data_dir: /tmp/imf
log_files:
  - path: /var/log/system.log
    type: system
  - path: /var/log/app.log
    type: application
plugins:
  collectors:
    - log_file_collector
    - system_metrics_collector
  detectors:
    - log_pattern_detector
    - threshold_detector
  remediators:
    - system_remediation
thresholds:
  cpu_usage:
    warning: 80
    critical: 95
  memory_usage:
    warning: 85
    critical: 95
  disk_usage:
    warning: 85
    critical: 95
